### ISSUE TITLE
Newest version on master fails on build

### ISSUE THREAD

**Issue by tjeppesen** [jujoramos/geode-support-shell#6]
tjeppesen@Tommys-MacBook-Pro:~/git/geode-support-shell (master): ./gradlew clean build
Downloading https://services.gradle.org/distributions/gradle-4.4-bin.zip
........................................................................
Unzipping /Users/tjeppesen/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4-bin.zip to /Users/tjeppesen/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi
Set executable permissions for: /Users/tjeppesen/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4/bin/gradle
Starting a Gradle Daemon (subsequent builds will be faster)
Download https://jcenter.bintray.com/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.pom
Download https://jcenter.bintray.com/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar

> Task :compileJava 
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test 
╔═════════════════════════════════════════════════════════════════════════════════════╦═══════╦═══════╦═══════╦═════╦═════════╗
║/uncorrupted/cluster1-server1.gfs                                                    ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──CachePerfStats[RegionStats-gatewayEventIdIndexMetaData].getInitialImagesInProgress║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].initialImageRequestsInProgress               ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].replyWaitsInProgress                         ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║/uncorrupted/cluster1-server2.gfs                                                    ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DLockStats[dlockStats].grantWaitsInProgress                                       ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].replyWaitsInProgress                         ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].putLocalInProgress                                  ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].sendReplicationInProgress                           ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║/uncorrupted/cluster2-locator.gz                                                     ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──LocatorStats[192.168.1.7-0.0.0.0/0.0.0.0:12334].requestsInProgress                ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║/uncorrupted/cluster2-server1.gfs                                                    ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].replyWaitsInProgress                         ║0.00   ║2.00   ║0.00   ║0.00 ║0.08     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].putLocalInProgress                                  ║0.00   ║2.00   ║0.00   ║0.00 ║0.08     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].sendReplicationInProgress                           ║0.00   ║2.00   ║0.00   ║0.00 ║0.08     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║/uncorrupted/cluster2-server2.gfs                                                    ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].replyWaitsInProgress                         ║0.00   ║3.00   ║0.00   ║0.00 ║0.06     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──DistributionStats[distributionStats].syncSocketWritesInProgress                   ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].putLocalInProgress                                  ║0.00   ║2.00   ║0.00   ║0.00 ║0.05     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].putRemoteInProgress                                 ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PartitionedRegionStats[/test].sendReplicationInProgress                           ║0.00   ║2.00   ║0.00   ║0.00 ║0.04     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║/uncorrupted/sampleClient.gfs                                                        ║Minimum║Maximum║Average║Last ║Standard ║
║                                                                                     ║       ║       ║       ║Value║Deviation║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──ClientSendStats[ClientSendStats-default-192.168.1.7:10102].putSendsInProgress     ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──ClientStats[ClientStats-default-192.168.1.7:10101].putsInProgress                 ║0.00   ║1.00   ║0.00   ║0.00 ║0.03     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──ClientStats[ClientStats-default-192.168.1.7:10102].putsInProgress                 ║0.00   ║1.00   ║0.00   ║0.00 ║0.03     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PoolStats[default->[any servers]].clientOpSendsInProgress                         ║0.00   ║1.00   ║0.00   ║0.00 ║0.02     ║
╠═════════════════════════════════════════════════════════════════════════════════════╬═══════╬═══════╬═══════╬═════╬═════════╣
║└──PoolStats[default->[any servers]].clientOpsInProgress                             ║0.00   ║1.00   ║0.00   ║0.00 ║0.04     ║
╚═════════════════════════════════════════════════════════════════════════════════════╩═══════╩═══════╩═══════╩═════╩═════════╝

╔══════════════════════════════╦═══════════╗
║File Name                     ║Error      ║
║                              ║Description║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gfs║Unexpected ║
║                              ║token byte ║
║                              ║value: 67  ║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gz ║Not in GZIP║
║                              ║format     ║
╚══════════════════════════════╩═══════════╝

╔═════════════════════════════════╦═══════╗
║File Name                        ║Matches║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster1-locator.gz ║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster1-server1.gfs║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster1-server2.gfs║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster2-locator.gz ║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster2-server1.gfs║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/cluster2-server2.gfs║true   ║
╠═════════════════════════════════╬═══════╣
║/uncorrupted/sampleClient.gfs    ║true   ║
╚═════════════════════════════════╩═══════╝

╔══════════════════════════════╦═══════════╗
║File Name                     ║Error      ║
║                              ║Description║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gfs║Unexpected ║
║                              ║token byte ║
║                              ║value: 67  ║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gz ║Not in GZIP║
║                              ║format     ║
╚══════════════════════════════╩═══════════╝

╔═════════════════════════════════╦═══════╦═════════╦═══════════════╦═══════════╦═══════════╗
║File Name                        ║Product║Operating║Time Zone      ║Start Time ║Finish Time║
║                                 ║Version║System   ║               ║           ║           ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster1-locator.gz ║GemFire║Mac OS X ║Europe/Dublin  ║22-Mar-2018║22-Mar-2018║
║                                 ║9.3.0  ║10.13.3  ║               ║14:06:09   ║15:17:05   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster1-server1.gfs║GemFire║Mac OS X ║Europe/Dublin  ║22-Mar-2018║22-Mar-2018║
║                                 ║9.3.0  ║10.13.3  ║               ║14:06:22   ║15:17:06   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster1-server2.gfs║GemFire║Mac OS X ║Europe/Dublin  ║22-Mar-2018║22-Mar-2018║
║                                 ║9.3.0  ║10.13.3  ║               ║14:06:22   ║15:17:05   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster2-locator.gz ║GemFire║Mac OS X ║America/Chicago║22-Mar-2018║22-Mar-2018║
║                                 ║8.2.8  ║10.13.3  ║               ║09:06:24   ║10:17:04   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster2-server1.gfs║GemFire║Mac OS X ║America/Chicago║22-Mar-2018║22-Mar-2018║
║                                 ║8.2.8  ║10.13.3  ║               ║09:06:33   ║10:17:03   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/cluster2-server2.gfs║GemFire║Mac OS X ║America/Chicago║22-Mar-2018║22-Mar-2018║
║                                 ║8.2.8  ║10.13.3  ║               ║09:06:33   ║10:17:04   ║
╠═════════════════════════════════╬═══════╬═════════╬═══════════════╬═══════════╬═══════════╣
║/uncorrupted/sampleClient.gfs    ║GemFire║Mac OS X ║Europe/Dublin  ║22-Mar-2018║22-Mar-2018║
║                                 ║9.1.0  ║10.13.3  ║               ║14:06:51   ║15:07:08   ║
╚═════════════════════════════════╩═══════╩═════════╩═══════════════╩═══════════╩═══════════╝

╔══════════════════════════════╦═══════════╗
║File Name                     ║Error      ║
║                              ║Description║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gfs║Unexpected ║
║                              ║token byte ║
║                              ║value: 67  ║
╠══════════════════════════════╬═══════════╣
║/corrupted/unparseableFile.gz ║Not in GZIP║
║                              ║format     ║
╚══════════════════════════════╩═══════════╝

╔════════════════════════╦═══════╦══════════════════════════╦════════════════════╦═══════════╦═══════════╗
║File Name               ║Product║Operating System          ║Time Zone           ║Start Time ║Finish Time║
║                        ║Version║                          ║                    ║           ║           ║
╠════════════════════════╬═══════╬══════════════════════════╬════════════════════╬═══════════╬═══════════╣
║/parseable/member_8X.log║8.2.0  ║x86_64 Mac OS X 10.13.6   ║Europe/Dublin       ║24-Aug-2018║24-Aug-2018║
║                        ║       ║                          ║                    ║14:52:44   ║15:07:57   ║
╠════════════════════════╬═══════╬══════════════════════════╬════════════════════╬═══════════╬═══════════╣
║/parseable/member_9X.log║9.4.0  ║amd64 Linux               ║America/Buenos_Aires║17-Apr-2018║17-Apr-2018║
║                        ║       ║3.10.0-862.11.6.el7.x86_64║                    ║05:19:48   ║05:20:45   ║
╠════════════════════════╬═══════╬══════════════════════════╬════════════════════╬═══════════╬═══════════╣
║/parseable/noHeader.log ║       ║                          ║                    ║06-Sep-2018║06-Sep-2018║
║                        ║       ║                          ║                    ║03:03:20   ║05:12:14   ║
╚════════════════════════╩═══════╩══════════════════════════╩════════════════════╩═══════════╩═══════════╝

╔══════════════════════════════╦═══════════╗
║File Name                     ║Error      ║
║                              ║Description║
╠══════════════════════════════╬═══════════╣
║/unparseable/unknownFormat.log║Log format ║
║                              ║not        ║
║                              ║recognized.║
╚══════════════════════════════╩═══════════╝

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(,true) [0] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(,false) [1] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(Australia/Sydney,true) [2] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(Australia/Sydney,false) [3] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(America/Argentina/Buenos_Aires,true) [4] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(America/Argentina/Buenos_Aires,false) [5] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(Asia/Shanghai,true) [6] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnErrorAndMetadataTablesInOrder(Asia/Shanghai, false) [7] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:220

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(,true) [0] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(,false) [1] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(Australia/Sydney,true) [2] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(Australia/Sydney,false) [3] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(America/Argentina/Buenos_Aires,true) [4] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(America/Argentina/Buenos_Aires,false) [5] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(Asia/Shanghai,true) [6] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156

org.apache.geode.support.command.logs.ShowLogsMetadataCommandIntegrationTest > showLogsMetadataShouldReturnOnlyMetadataTableIfParsingSucceedsForAllFiles(Asia/Shanghai, false) [7] FAILED
    org.junit.ComparisonFailure at ShowLogsMetadataCommandIntegrationTest.java:156
╔════════════════════════╦═══════╗
║File Name               ║Matches║
╠════════════════════════╬═══════╣
║/parseable/member_8X.log║true   ║
╠════════════════════════╬═══════╣
║/parseable/member_9X.log║false  ║
╠════════════════════════╬═══════╣
║/parseable/noHeader.log ║false  ║
╚════════════════════════╩═══════╝

╔══════════════════════════════╦═══════════╗
║File Name                     ║Error      ║
║                              ║Description║
╠══════════════════════════════╬═══════════╣
║/unparseable/unknownFormat.log║Log format ║
║                              ║not        ║
║                              ║recognized.║
╚══════════════════════════════╩═══════════╝

org.apache.geode.support.service.logs.LogsServiceIntegrationTest > parseIntervalShouldReturnBothParsingErrorsAndParsingSuccessesWhenParsingSucceedsForSomeFilesAndFailsForOthers FAILED
    org.junit.ComparisonFailure at LogsServiceIntegrationTest.java:83

org.apache.geode.support.service.logs.LogsServiceIntegrationTest > parseMetadataShouldReturnBothParsingErrorsAndParsingSuccessesWhenParsingSucceedsForSomeFilesAndFailsForOthers FAILED
    org.junit.ComparisonFailure at LogsServiceIntegrationTest.java:141

org.apache.geode.support.service.logs.internal.Log4JParserIntegrationTest > parseLogFileMetadataShouldWorkCorrectly FAILED
    org.junit.ComparisonFailure at Log4JParserIntegrationTest.java:65

org.apache.geode.support.service.logs.internal.Log4JParserIntegrationTest > parseLogFileIntervalShouldWorkCorrectly FAILED
    org.junit.ComparisonFailure at Log4JParserIntegrationTest.java:48

org.apache.geode.support.service.logs.internal.Log4JParserTest > buildMetadataWithIntervalShouldReturnTheLogMetadataOnlyWithTheIntervalCovered FAILED
    org.junit.ComparisonFailure at Log4JParserTest.java:225

org.apache.geode.support.service.logs.internal.Log4JParserTest > buildMetadataShouldReturnFullLogMetadata FAILED
    org.junit.ComparisonFailure at Log4JParserTest.java:292

org.apache.geode.support.service.logs.internal.Log4JParserTest > buildMetadataShouldReturnOnlyTheIntervalCoveredIfNoExtraMetadataIsFound FAILED
    org.junit.ComparisonFailure at Log4JParserTest.java:274

org.apache.geode.support.service.logs.internal.Log4JParserTest > parseLogFileIntervalShouldReturnTheLogMetadataWithTheIntervalCoveredOnly FAILED
    org.junit.ComparisonFailure

org.apache.geode.support.service.logs.internal.CustomLogFilePatternReceiverIntegrationTest > parseLineShouldCorrectlyParseStringIntoLoggingEvent FAILED
    org.junit.ComparisonFailure at CustomLogFilePatternReceiverIntegrationTest.java:93

303 tests completed, 25 failed, 6 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/tjeppesen/git/geode-support-shell/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 35s
7 actionable tasks: 7 executed

**Comment by jujoramos** [comment]
Hello @tjeppesen,

Thanks for submitting the issue!.
The problem is purely related to the test classes (a bad design on my side when dealign with the default `ZoneId`), so you should be able to still create the jar and use the tool, just run `./gradlew clean build -x test`. I'll fix the tests as soon as I can.
Cheers.
